alter table CUBAPLANER_SESSION add constraint FK_CUBAPLANER_SESSION_ON_SPEAKER foreign key (SPEAKER_ID) references CUBAPLANER_SPEAKER(ID);
create index IDX_CUBAPLANER_SESSION_ON_SPEAKER on CUBAPLANER_SESSION (SPEAKER_ID);
